config/routes.rb
Rails.application.routes.draw do
  # get "/" => 'homes#top', as: 'root_path'

  root 'homes#top'
  resources :books, only: [:index, :create, :show, :edit, :update, :destroy] 
  
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @edit_book= Book.find(params[:id])
  end

  def update
    @edit_book = Book.find(params[:id])
    if @edit_book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@edit_book.id)
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @edit_book.errors.any? %>
  <%= @edit_book.errors.count %>edit_edit_error prohibited this book from being saved:
  <ul>
    <% @edit_book.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
      <% end %>
  </ul>
<% end %>


  <%= form_with model: @edit_book, url: book_path(@edit_book.id), method: :patch do |f| %>
    <h4>title</h4>
    <%= f.text_field :title %>
    
    <h4>body</h4>
    <%= f.text_area :body %>

    <%= f.submit 'Update Book' %>
  <% end %>
  
  <%= link_to 'show', book_path(params[:id]) %>
  <%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="top-outer">

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th clospan="3" ></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to 'Show', book_path(book.id) %></td>
      <td><%= link_to 'Edit', edit_book_path(book.id) %></td>
      <td><%= link_to 'Destroy', book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="under-box">
  <h1>New Book</h1>
  <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <%= form_with model: Book.new do |f| %>
    <h4>title</h4>
    <%= f.text_field :title %>
    <h4>body</h4>
    <%= f.text_area :body %>
    <br>
    <%= f.submit 'Create Book' %>
  <% end %>
</div>

</div>

app/views/books/show.html.erb
<div class="show-top-outer">
    <div class="flash-notice">
        <%= flash[:notice] %>
    </div>
    <div>
        <span class="show-head">Title:</span>
        <span class="show-in"><%= @book.title %></span>
    </div>
    <div>
        <span class="show-head">Body:</span>
        <span class="show-in"><%= @book.body %></span>
    </div>
    <%= link_to 'Edit', edit_book_path(params[:id]) %>
    <%= link_to 'Back', books_path %>
</div>

app/views/homes/top.html.erb
<h1>ようこそBookersへ！</h1>

<h5>
  Bookers では、さまざまな書籍に関するあなたの意見や</br>
  印象を共有し交換することができます
</h5>
<%= link_to 'start', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>